name: Lighthouse Performance Tests

on:
  schedule:
    - cron: "0 17 * * *" # Run at 10:00 AM MST (5:00 PM UTC)
  push:
    branches: ["main"] # Add or modify branches as needed
  workflow_dispatch: # Allow manual triggering

jobs:
  lighthouse-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    environment: Production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser

      - name: Install dependencies
        run: npm install

      - name: Create results directory
        run: mkdir -p lighthouse-results

      - name: Run Lighthouse tests
        run: npx ts-node -P tsconfig.scripts.json scripts/run-lighthouse-tests.ts
        env:
          CHROME_PATH: /usr/bin/chromium-browser

      - name: Upload Lighthouse results
        if: always() # Upload even if tests fail
        uses: actions/upload-artifact@v4
        with:
          name: lighthouse-results
          path: lighthouse-results/
          retention-days: 7
