name: Lighthouse CI
on:
  push:
    branches: [main] # Adjust based on your branch structure
  workflow_dispatch: # Allow manual triggering

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v12
        with:
          urls: |
            https://chasecee.com/
            https://www.striderintel.com/about
            https://inmoment.com/blog
          uploadArtifacts: true
          temporaryPublicStorage: true
