name: PageSpeed Insights Cron

on:
  schedule:
    - cron: "0 0 * * *" # Run daily at midnight UTC
  workflow_dispatch: # Allow manual triggering

jobs:
  run-pagespeed-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 30 # Adjust as needed, up to 360 (6 hours)
    environment: Production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Run PageSpeed tests
        run: npx ts-node -P tsconfig.scripts.json scripts/run-pagespeed-tests.ts
        env:
          GOOGLE_SERVICE_ACCOUNT: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}
          GOOGLE_SHEETS_SHEET_ID: ${{ secrets.GOOGLE_SHEETS_SHEET_ID }}
          PAGESPEED_API_KEY: ${{ secrets.PAGESPEED_API_KEY }}
